# Generated by Django 2.2.7 on 2019-12-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191206_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='cerification_type',
            new_name='certificate_type',
        ),
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateField(),
        ),
    ]
