# Generated by Django 2.2.7 on 2019-12-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191206_2127'),
        ('web', '0002_auto_20191208_1724'),
    ]

    operations = [
    ]
